const data = 
  [
      {
        no:1,
        kota: "Jakarta",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:2,
        kota: "Jawa Barat",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:3,
        kota: "Jawa Tengah",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:4,
        kota: "Jawa Timur",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:5,
        kota: "Banten",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      { 
        no:6,
        kota: "Kalimantan Timur",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:7,
        kota: "Bali",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:8,
        kota: "Sumatera Utara",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:9,
        kota: "Riau",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:10,
        kota: "Sulawesi Selatan",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:11,
        kota: "Sumatera Barat",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:12,
        kota: "Nusa Tenggara Timur",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:13,
        kota: "Kalimantan Selatan",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:14,
        kota: "Sumatera Selatan",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:15,
        kota: "Lampung",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:16,
        kota: "Kepulauan Riau",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:17,
        kota: "Bangka Belitung",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:18,
        kota: "Kalimantan Barat",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:19,
        kota: "Sulawesi Tengah",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:20,
        kota: "Kalimantan Tengah",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:21,
        kota: "Sulawesi Utara",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:22,
        kota: "Papua",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:23,
        kota: "Aceh",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:24,
        kota: "Jambi",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:25,
        kota: "Nusa Tenggara Barat",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:26,
        kota: "Papua Barat",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:27,
        kota: "Bengkulu",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:28,
        kota: "Sulawesi Tenggara",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:29,
        kota: "Maluku",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:30,
        kota: "Sulawesi Barat",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:31,
        kota: "Maluku Utara",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:32,
        kota: "Gorontalo",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
      {
        no:33,
        kota: "Yogyakarta",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      }, 
      {
        no:34,
        kota: "Kalimantan Utara",
        kasus: 0,
        sembuh: 0,
        meninggal: 0,
        dirawat: 0,
      },
    ];
  
  export default data;